# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61\x63\x63ount_status.proto\x12\x0f\x61\x63\x63ount_service*<\n\x0bLoginStatus\x12\x0c\n\x08LoggedIn\x10\x00\x12\r\n\tLoggedOut\x10\x01\x12\x10\n\x0cLogginFailed\x10\x02*7\n\rAccountStatus\x12\x12\n\x0e\x41\x63\x63ountStopped\x10\x00\x12\x12\n\x0e\x41\x63\x63ountActived\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_status_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINSTATUS._serialized_start=41
  _LOGINSTATUS._serialized_end=101
  _ACCOUNTSTATUS._serialized_start=103
  _ACCOUNTSTATUS._serialized_end=158
# @@protoc_insertion_point(module_scope)
