# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import name_pb2 as name__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x0f\x61\x63\x63ount_service\x1a\nname.proto\"j\n\x11NewAccountRequest\x12\x11\n\tarea_code\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12!\n\tnick_name\x18\x04 \x01(\x0b\x32\x0e.cashmere.Name\"$\n\x12NewAccountResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"b\n\x0fRegisterRequest\x12\x17\n\x0forganization_id\x18\x01 \x01(\t\x12\x15\n\rdepartment_id\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\"\"\n\x10RegisterResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"O\n\x15\x43hangeOwnPhoneRequest\x12\x11\n\told_phone\x18\x01 \x01(\t\x12\x11\n\tnew_phone\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"(\n\x16\x43hangePhoneOwnResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"B\n\x1a\x41\x64\x64\x41\x63\x63ountIntoGroupRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x10\n\x08group_id\x18\x02 \x01(\t\"-\n\x1b\x41\x64\x64\x41\x63\x63ountIntoGroupResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"E\n\x1dRemoveAccountFromGroupRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x10\n\x08group_id\x18\x02 \x01(\t\"0\n\x1eRemoveAccountFromGroupResponse\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWACCOUNTREQUEST._serialized_start=46
  _NEWACCOUNTREQUEST._serialized_end=152
  _NEWACCOUNTRESPONSE._serialized_start=154
  _NEWACCOUNTRESPONSE._serialized_end=190
  _REGISTERREQUEST._serialized_start=192
  _REGISTERREQUEST._serialized_end=290
  _REGISTERRESPONSE._serialized_start=292
  _REGISTERRESPONSE._serialized_end=326
  _CHANGEOWNPHONEREQUEST._serialized_start=328
  _CHANGEOWNPHONEREQUEST._serialized_end=407
  _CHANGEPHONEOWNRESPONSE._serialized_start=409
  _CHANGEPHONEOWNRESPONSE._serialized_end=449
  _ADDACCOUNTINTOGROUPREQUEST._serialized_start=451
  _ADDACCOUNTINTOGROUPREQUEST._serialized_end=517
  _ADDACCOUNTINTOGROUPRESPONSE._serialized_start=519
  _ADDACCOUNTINTOGROUPRESPONSE._serialized_end=564
  _REMOVEACCOUNTFROMGROUPREQUEST._serialized_start=566
  _REMOVEACCOUNTFROMGROUPREQUEST._serialized_end=635
  _REMOVEACCOUNTFROMGROUPRESPONSE._serialized_start=637
  _REMOVEACCOUNTFROMGROUPRESPONSE._serialized_end=685
# @@protoc_insertion_point(module_scope)
