# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import account_pb2 as account__pb2
import login_pb2 as login__pb2
import password_pb2 as password__pb2


class AccountGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/account_service.AccountGrpc/Login',
                request_serializer=login__pb2.LoginRequest.SerializeToString,
                response_deserializer=login__pb2.LoginResponse.FromString,
                )
        self.NewAccount = channel.unary_unary(
                '/account_service.AccountGrpc/NewAccount',
                request_serializer=account__pb2.NewAccountRequest.SerializeToString,
                response_deserializer=account__pb2.NewAccountResponse.FromString,
                )
        self.AddAccountIntoGroup = channel.unary_unary(
                '/account_service.AccountGrpc/AddAccountIntoGroup',
                request_serializer=account__pb2.AddAccountIntoGroupRequest.SerializeToString,
                response_deserializer=account__pb2.AddAccountIntoGroupResponse.FromString,
                )
        self.RemoveAccountFromGroup = channel.unary_unary(
                '/account_service.AccountGrpc/RemoveAccountFromGroup',
                request_serializer=account__pb2.RemoveAccountFromGroupRequest.SerializeToString,
                response_deserializer=account__pb2.RemoveAccountFromGroupResponse.FromString,
                )
        self.ChangeOwnPassword = channel.unary_unary(
                '/account_service.AccountGrpc/ChangeOwnPassword',
                request_serializer=password__pb2.ChangeOwnPasswordRequest.SerializeToString,
                response_deserializer=password__pb2.ChangeOwnPasswordResponse.FromString,
                )
        self.ChangeAccountStatus = channel.unary_unary(
                '/account_service.AccountGrpc/ChangeAccountStatus',
                request_serializer=account__pb2.ChangeAccountStatusRequest.SerializeToString,
                response_deserializer=account__pb2.ChangeAccountStatusResponse.FromString,
                )
        self.ChangeAccountPassword = channel.unary_unary(
                '/account_service.AccountGrpc/ChangeAccountPassword',
                request_serializer=password__pb2.ChangeAccountPasswordRequest.SerializeToString,
                response_deserializer=password__pb2.ChangeAccountPasswordResponse.FromString,
                )


class AccountGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """登录
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewAccount(self, request, context):
        """rpc Logout (LogoutRequest) returns (LogoutResponse);
        rpc Register (RegisterRequest) returns (RegisterResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAccountIntoGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAccountFromGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeOwnPassword(self, request, context):
        """修改自身密码
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeAccountStatus(self, request, context):
        """修改帐号状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeAccountPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=login__pb2.LoginRequest.FromString,
                    response_serializer=login__pb2.LoginResponse.SerializeToString,
            ),
            'NewAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.NewAccount,
                    request_deserializer=account__pb2.NewAccountRequest.FromString,
                    response_serializer=account__pb2.NewAccountResponse.SerializeToString,
            ),
            'AddAccountIntoGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAccountIntoGroup,
                    request_deserializer=account__pb2.AddAccountIntoGroupRequest.FromString,
                    response_serializer=account__pb2.AddAccountIntoGroupResponse.SerializeToString,
            ),
            'RemoveAccountFromGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAccountFromGroup,
                    request_deserializer=account__pb2.RemoveAccountFromGroupRequest.FromString,
                    response_serializer=account__pb2.RemoveAccountFromGroupResponse.SerializeToString,
            ),
            'ChangeOwnPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeOwnPassword,
                    request_deserializer=password__pb2.ChangeOwnPasswordRequest.FromString,
                    response_serializer=password__pb2.ChangeOwnPasswordResponse.SerializeToString,
            ),
            'ChangeAccountStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeAccountStatus,
                    request_deserializer=account__pb2.ChangeAccountStatusRequest.FromString,
                    response_serializer=account__pb2.ChangeAccountStatusResponse.SerializeToString,
            ),
            'ChangeAccountPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeAccountPassword,
                    request_deserializer=password__pb2.ChangeAccountPasswordRequest.FromString,
                    response_serializer=password__pb2.ChangeAccountPasswordResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'account_service.AccountGrpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccountGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account_service.AccountGrpc/Login',
            login__pb2.LoginRequest.SerializeToString,
            login__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account_service.AccountGrpc/NewAccount',
            account__pb2.NewAccountRequest.SerializeToString,
            account__pb2.NewAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddAccountIntoGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account_service.AccountGrpc/AddAccountIntoGroup',
            account__pb2.AddAccountIntoGroupRequest.SerializeToString,
            account__pb2.AddAccountIntoGroupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveAccountFromGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account_service.AccountGrpc/RemoveAccountFromGroup',
            account__pb2.RemoveAccountFromGroupRequest.SerializeToString,
            account__pb2.RemoveAccountFromGroupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeOwnPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account_service.AccountGrpc/ChangeOwnPassword',
            password__pb2.ChangeOwnPasswordRequest.SerializeToString,
            password__pb2.ChangeOwnPasswordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeAccountStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account_service.AccountGrpc/ChangeAccountStatus',
            account__pb2.ChangeAccountStatusRequest.SerializeToString,
            account__pb2.ChangeAccountStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeAccountPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account_service.AccountGrpc/ChangeAccountPassword',
            password__pb2.ChangeAccountPasswordRequest.SerializeToString,
            password__pb2.ChangeAccountPasswordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
