# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import account_pb2 as account__pb2
import login_pb2 as login__pb2


class AccountGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/account_service.AccountGrpc/Login',
                request_serializer=login__pb2.LoginRequest.SerializeToString,
                response_deserializer=login__pb2.LoginResponse.FromString,
                )
        self.NewAccount = channel.unary_unary(
                '/account_service.AccountGrpc/NewAccount',
                request_serializer=account__pb2.NewAccountRequest.SerializeToString,
                response_deserializer=account__pb2.NewAccountResponse.FromString,
                )
        self.AddAccountIntoGroup = channel.unary_unary(
                '/account_service.AccountGrpc/AddAccountIntoGroup',
                request_serializer=account__pb2.AddAccountIntoGroupRequest.SerializeToString,
                response_deserializer=account__pb2.AddAccountIntoGroupResponse.FromString,
                )
        self.RemoveAccountFromGroup = channel.unary_unary(
                '/account_service.AccountGrpc/RemoveAccountFromGroup',
                request_serializer=account__pb2.RemoveAccountFromGroupRequest.SerializeToString,
                response_deserializer=account__pb2.RemoveAccountFromGroupResponse.FromString,
                )


class AccountGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """登录
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewAccount(self, request, context):
        """rpc Logout (LogoutRequest) returns (LogoutResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAccountIntoGroup(self, request, context):
        """rpc Register (RegisterRequest) returns (RegisterResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAccountFromGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=login__pb2.LoginRequest.FromString,
                    response_serializer=login__pb2.LoginResponse.SerializeToString,
            ),
            'NewAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.NewAccount,
                    request_deserializer=account__pb2.NewAccountRequest.FromString,
                    response_serializer=account__pb2.NewAccountResponse.SerializeToString,
            ),
            'AddAccountIntoGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAccountIntoGroup,
                    request_deserializer=account__pb2.AddAccountIntoGroupRequest.FromString,
                    response_serializer=account__pb2.AddAccountIntoGroupResponse.SerializeToString,
            ),
            'RemoveAccountFromGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAccountFromGroup,
                    request_deserializer=account__pb2.RemoveAccountFromGroupRequest.FromString,
                    response_serializer=account__pb2.RemoveAccountFromGroupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'account_service.AccountGrpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccountGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account_service.AccountGrpc/Login',
            login__pb2.LoginRequest.SerializeToString,
            login__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account_service.AccountGrpc/NewAccount',
            account__pb2.NewAccountRequest.SerializeToString,
            account__pb2.NewAccountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddAccountIntoGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account_service.AccountGrpc/AddAccountIntoGroup',
            account__pb2.AddAccountIntoGroupRequest.SerializeToString,
            account__pb2.AddAccountIntoGroupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveAccountFromGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/account_service.AccountGrpc/RemoveAccountFromGroup',
            account__pb2.RemoveAccountFromGroupRequest.SerializeToString,
            account__pb2.RemoveAccountFromGroupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
