# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: answer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61nswer.proto\x12\x08\x63\x61shmere\"9\n\x10NewAnswerRequest\x12\x13\n\x0bquestion_id\x18\x01 \x01(\t\x12\x10\n\x08\x63ontents\x18\x02 \x01(\t\"#\n\x11NewAnswerResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"<\n\x11\x45\x64itAnswerRequest\x12\x11\n\tanswer_id\x18\x01 \x01(\t\x12\x14\n\x0cnew_contents\x18\x02 \x01(\t\"$\n\x12\x45\x64itAnswerResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"=\n\x13RemoveAnswerRequest\x12\x13\n\x0bquestion_id\x18\x01 \x01(\t\x12\x11\n\tanswer_id\x18\x02 \x01(\t\"&\n\x14RemoveAnswerResponse\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'answer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWANSWERREQUEST._serialized_start=26
  _NEWANSWERREQUEST._serialized_end=83
  _NEWANSWERRESPONSE._serialized_start=85
  _NEWANSWERRESPONSE._serialized_end=120
  _EDITANSWERREQUEST._serialized_start=122
  _EDITANSWERREQUEST._serialized_end=182
  _EDITANSWERRESPONSE._serialized_start=184
  _EDITANSWERRESPONSE._serialized_end=220
  _REMOVEANSWERREQUEST._serialized_start=222
  _REMOVEANSWERREQUEST._serialized_end=283
  _REMOVEANSWERRESPONSE._serialized_start=285
  _REMOVEANSWERRESPONSE._serialized_end=323
# @@protoc_insertion_point(module_scope)
