# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: area.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import name_pb2 as name__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\narea.proto\x12\x08\x63\x61shmere\x1a\nname.proto\"s\n\x0eNewAreaRequest\x12\x1c\n\x04name\x18\x01 \x01(\x0b\x32\x0e.cashmere.Name\x12\x11\n\tparent_id\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\"\n\x05level\x18\x04 \x01(\x0e\x32\x13.cashmere.AreaLevel\"!\n\x0fNewAreaResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"a\n\x0f\x45\x64itAreaRequest\x12\x0f\n\x07\x61rea_id\x18\x01 \x01(\t\x12\x15\n\rnew_parent_id\x18\x03 \x01(\t\x12&\n\tnew_level\x18\x04 \x01(\x0e\x32\x13.cashmere.AreaLevel\"\"\n\x10\x45\x64itAreaResponse\x12\x0e\n\x06result\x18\x01 \x01(\t*:\n\tAreaLevel\x12\x0b\n\x07\x43ountry\x10\x00\x12\x0c\n\x08Province\x10\x01\x12\x08\n\x04\x43ity\x10\x02\x12\x08\n\x04\x41rea\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'area_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AREALEVEL._serialized_start=323
  _AREALEVEL._serialized_end=381
  _NEWAREAREQUEST._serialized_start=36
  _NEWAREAREQUEST._serialized_end=151
  _NEWAREARESPONSE._serialized_start=153
  _NEWAREARESPONSE._serialized_end=186
  _EDITAREAREQUEST._serialized_start=188
  _EDITAREAREQUEST._serialized_end=285
  _EDITAREARESPONSE._serialized_start=287
  _EDITAREARESPONSE._serialized_end=321
# @@protoc_insertion_point(module_scope)
