# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asset_collection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import name_pb2 as name__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61sset_collection.proto\x12\nio.knitter\x1a\nname.proto\"\x94\x01\n\x19NewAssetCollectionRequest\x12\x1c\n\x04name\x18\x01 \x01(\x0b\x32\x0e.cashmere.Name\x12\x17\n\x0finner_root_path\x18\x02 \x01(\t\x12\x1a\n\x12\x65xternal_root_path\x18\x03 \x01(\t\x12\x0f\n\x07picture\x18\x04 \x01(\x0c\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\",\n\x1aNewAssetCollectionResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"A\n(GetAssetCollectionAssetTotalCountRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\"@\n)GetAssetCollectionAssetTotalCountResponse\x12\x13\n\x0btotal_count\x18\x01 \x01(\x04\"D\n+GetAssetCollectionAssemblyTotalCountRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\"C\n,GetAssetCollectionAssemblyTotalCountResponse\x12\x13\n\x0btotal_count\x18\x01 \x01(\x04\"k\n#GetAssetCollectionAssetsPageRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x12\n\npage_index\x18\x02 \x01(\r\x12\x19\n\x11total_pages_count\x18\x03 \x01(\r\"6\n$GetAssetCollectionAssetsPageResponse\x12\x0e\n\x06\x61ssets\x18\x01 \x03(\x0c\"T\n\'GetAssetCollectionAssembliesPageRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x12\n\npage_index\x18\x02 \x01(\r\">\n(GetAssetCollectionAssembliesPageResponse\x12\x12\n\nassemblies\x18\x01 \x03(\x0c\"l\n MarkAssetCollectionStatusRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x31\n\x06status\x18\x02 \x01(\x0e\x32!.io.knitter.AssetCollectionStatus\"V\n!MarkAssetCollectionStatusResponse\x12\x31\n\x06status\x18\x01 \x01(\x0e\x32!.io.knitter.AssetCollectionStatus*O\n\x15\x41ssetCollectionStatus\x12\x19\n\x15\x41ssetCollectionClosed\x10\x00\x12\x1b\n\x17\x41ssetCollectionOpenning\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asset_collection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ASSETCOLLECTIONSTATUS._serialized_start=1032
  _ASSETCOLLECTIONSTATUS._serialized_end=1111
  _NEWASSETCOLLECTIONREQUEST._serialized_start=51
  _NEWASSETCOLLECTIONREQUEST._serialized_end=199
  _NEWASSETCOLLECTIONRESPONSE._serialized_start=201
  _NEWASSETCOLLECTIONRESPONSE._serialized_end=245
  _GETASSETCOLLECTIONASSETTOTALCOUNTREQUEST._serialized_start=247
  _GETASSETCOLLECTIONASSETTOTALCOUNTREQUEST._serialized_end=312
  _GETASSETCOLLECTIONASSETTOTALCOUNTRESPONSE._serialized_start=314
  _GETASSETCOLLECTIONASSETTOTALCOUNTRESPONSE._serialized_end=378
  _GETASSETCOLLECTIONASSEMBLYTOTALCOUNTREQUEST._serialized_start=380
  _GETASSETCOLLECTIONASSEMBLYTOTALCOUNTREQUEST._serialized_end=448
  _GETASSETCOLLECTIONASSEMBLYTOTALCOUNTRESPONSE._serialized_start=450
  _GETASSETCOLLECTIONASSEMBLYTOTALCOUNTRESPONSE._serialized_end=517
  _GETASSETCOLLECTIONASSETSPAGEREQUEST._serialized_start=519
  _GETASSETCOLLECTIONASSETSPAGEREQUEST._serialized_end=626
  _GETASSETCOLLECTIONASSETSPAGERESPONSE._serialized_start=628
  _GETASSETCOLLECTIONASSETSPAGERESPONSE._serialized_end=682
  _GETASSETCOLLECTIONASSEMBLIESPAGEREQUEST._serialized_start=684
  _GETASSETCOLLECTIONASSEMBLIESPAGEREQUEST._serialized_end=768
  _GETASSETCOLLECTIONASSEMBLIESPAGERESPONSE._serialized_start=770
  _GETASSETCOLLECTIONASSEMBLIESPAGERESPONSE._serialized_end=832
  _MARKASSETCOLLECTIONSTATUSREQUEST._serialized_start=834
  _MARKASSETCOLLECTIONSTATUSREQUEST._serialized_end=942
  _MARKASSETCOLLECTIONSTATUSRESPONSE._serialized_start=944
  _MARKASSETCOLLECTIONSTATUSRESPONSE._serialized_end=1030
# @@protoc_insertion_point(module_scope)
