# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asset.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import name_pb2 as name__pb2
import reference_pb2 as reference__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61sset.proto\x12\nio.knitter\x1a\nname.proto\x1a\x0freference.proto\"m\n\x0fNewAssetRequest\x12\x12\n\nlibrary_id\x18\x01 \x01(\t\x12\x1c\n\x04name\x18\x02 \x01(\x0b\x32\x0e.cashmere.Name\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0btemplate_id\x18\x04 \x01(\t\"\"\n\x10NewAssetResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"*\n\x16GetAssetSpecsesRequest\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\"*\n\x17GetAssetSpecsesResponse\x12\x0f\n\x07specses\x18\x01 \x03(\x0c\"*\n\x16GetAssetPrefabsRequest\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\"*\n\x17GetAssetPrefabsResponse\x12\x0f\n\x07prefabs\x18\x01 \x03(\x0c\"*\n\x16MarkAssetStatusRequest\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\t\")\n\x17MarkAssetStatusResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"U\n\x1aGetReferencedAssetsRequest\x12\x11\n\tmanage_id\x18\x01 \x01(\x05\x12\x11\n\tentity_id\x18\x02 \x01(\t\x12\x11\n\tasset_ids\x18\x03 \x03(\t\"-\n\x1bGetReferencedAssetsResponse\x12\x0e\n\x06\x61ssets\x18\x01 \x03(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asset_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWASSETREQUEST._serialized_start=56
  _NEWASSETREQUEST._serialized_end=165
  _NEWASSETRESPONSE._serialized_start=167
  _NEWASSETRESPONSE._serialized_end=201
  _GETASSETSPECSESREQUEST._serialized_start=203
  _GETASSETSPECSESREQUEST._serialized_end=245
  _GETASSETSPECSESRESPONSE._serialized_start=247
  _GETASSETSPECSESRESPONSE._serialized_end=289
  _GETASSETPREFABSREQUEST._serialized_start=291
  _GETASSETPREFABSREQUEST._serialized_end=333
  _GETASSETPREFABSRESPONSE._serialized_start=335
  _GETASSETPREFABSRESPONSE._serialized_end=377
  _MARKASSETSTATUSREQUEST._serialized_start=379
  _MARKASSETSTATUSREQUEST._serialized_end=421
  _MARKASSETSTATUSRESPONSE._serialized_start=423
  _MARKASSETSTATUSRESPONSE._serialized_end=464
  _GETREFERENCEDASSETSREQUEST._serialized_start=466
  _GETREFERENCEDASSETSREQUEST._serialized_end=551
  _GETREFERENCEDASSETSRESPONSE._serialized_start=553
  _GETREFERENCEDASSETSRESPONSE._serialized_end=598
# @@protoc_insertion_point(module_scope)
