# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asset_collection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import name_pb2 as name__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61sset_collection.proto\x12\nio.knitter\x1a\nname.proto\"\x94\x01\n\x19NewAssetCollectionRequest\x12\x1c\n\x04name\x18\x01 \x01(\x0b\x32\x0e.cashmere.Name\x12\x17\n\x0finner_root_path\x18\x02 \x01(\t\x12\x1a\n\x12\x65xternal_root_path\x18\x03 \x01(\t\x12\x0f\n\x07picture\x18\x04 \x01(\x0c\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\",\n\x1aNewAssetCollectionResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"j\n#GetAssetCollectionAssetsPageRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x12\n\npage_index\x18\x02 \x01(\r\x12\x18\n\x10total_page_count\x18\x03 \x01(\r\"6\n$GetAssetCollectionAssetsPageResponse\x12\x0e\n\x06\x61ssets\x18\x01 \x03(\x0c\"n\n\'GetAssetCollectionAssembliesPageRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x12\n\npage_index\x18\x02 \x01(\r\x12\x18\n\x10total_page_count\x18\x03 \x01(\r\">\n(GetAssetCollectionAssembliesPageResponse\x12\x12\n\nassemblies\x18\x01 \x03(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asset_collection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWASSETCOLLECTIONREQUEST._serialized_start=51
  _NEWASSETCOLLECTIONREQUEST._serialized_end=199
  _NEWASSETCOLLECTIONRESPONSE._serialized_start=201
  _NEWASSETCOLLECTIONRESPONSE._serialized_end=245
  _GETASSETCOLLECTIONASSETSPAGEREQUEST._serialized_start=247
  _GETASSETCOLLECTIONASSETSPAGEREQUEST._serialized_end=353
  _GETASSETCOLLECTIONASSETSPAGERESPONSE._serialized_start=355
  _GETASSETCOLLECTIONASSETSPAGERESPONSE._serialized_end=409
  _GETASSETCOLLECTIONASSEMBLIESPAGEREQUEST._serialized_start=411
  _GETASSETCOLLECTIONASSEMBLIESPAGEREQUEST._serialized_end=521
  _GETASSETCOLLECTIONASSEMBLIESPAGERESPONSE._serialized_start=523
  _GETASSETCOLLECTIONASSEMBLIESPAGERESPONSE._serialized_end=585
# @@protoc_insertion_point(module_scope)
