# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cashmere.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import country_pb2 as country__pb2
import language_code_pb2 as language__code__pb2
import group_pb2 as group__pb2
import property_type_pb2 as property__type__pb2
import name_pb2 as name__pb2
import color_pb2 as color__pb2
import data_pb2 as data__pb2
import data_server_pb2 as data__server__pb2
import data_stage_pb2 as data__stage__pb2
import file_data_pb2 as file__data__pb2
import sequence_data_pb2 as sequence__data__pb2
import set_data_pb2 as set__data__pb2
import area_pb2 as area__pb2
import entity_pb2 as entity__pb2
import manage_pb2 as manage__pb2
import manage_schema_pb2 as manage__schema__pb2
import view_pb2 as view__pb2
import event_pb2 as event__pb2
import work_pb2 as work__pb2
import task_pb2 as task__pb2
import phase_pb2 as phase__pb2
import work_node_pb2 as work__node__pb2
import procedure_pb2 as procedure__pb2
import tag_type_pb2 as tag__type__pb2
import tag_pb2 as tag__pb2
import tag_map_pb2 as tag__map__pb2
import comment_pb2 as comment__pb2
import question_pb2 as question__pb2
import answer_pb2 as answer__pb2
import season_pb2 as season__pb2
import position_pb2 as position__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61shmere.proto\x12\x08\x63\x61shmere\x1a\rcountry.proto\x1a\x13language_code.proto\x1a\x0bgroup.proto\x1a\x13property_type.proto\x1a\nname.proto\x1a\x0b\x63olor.proto\x1a\ndata.proto\x1a\x11\x64\x61ta_server.proto\x1a\x10\x64\x61ta_stage.proto\x1a\x0f\x66ile_data.proto\x1a\x13sequence_data.proto\x1a\x0eset_data.proto\x1a\narea.proto\x1a\x0c\x65ntity.proto\x1a\x0cmanage.proto\x1a\x13manage_schema.proto\x1a\nview.proto\x1a\x0b\x65vent.proto\x1a\nwork.proto\x1a\ntask.proto\x1a\x0bphase.proto\x1a\x0fwork_node.proto\x1a\x0fprocedure.proto\x1a\x0etag_type.proto\x1a\ttag.proto\x1a\rtag_map.proto\x1a\rcomment.proto\x1a\x0equestion.proto\x1a\x0c\x61nswer.proto\x1a\x0cseason.proto\x1a\x0eposition.proto2\x0e\n\x0c\x43\x61shmereGrpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cashmere_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CASHMEREGRPC._serialized_start=500
  _CASHMEREGRPC._serialized_end=514
# @@protoc_insertion_point(module_scope)
