# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comment.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcomment.proto\x12\x08\x63\x61shmere\"Y\n\x11NewCommentRequest\x12\x18\n\x10target_manage_id\x18\x01 \x01(\t\x12\x18\n\x10target_entity_id\x18\x02 \x01(\t\x12\x10\n\x08\x63ontents\x18\x03 \x01(\t\"$\n\x12NewCommentResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\">\n\x12\x45\x64itCommentRequest\x12\x12\n\ncomment_id\x18\x01 \x01(\t\x12\x14\n\x0cnew_contents\x18\x02 \x01(\t\"%\n\x13\x45\x64itCommentResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"^\n\x14RemoveCommentRequest\x12\x18\n\x10target_manage_id\x18\x01 \x01(\t\x12\x18\n\x10target_entity_id\x18\x02 \x01(\t\x12\x12\n\ncomment_id\x18\x03 \x01(\t\"\'\n\x15RemoveCommentResponse\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comment_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWCOMMENTREQUEST._serialized_start=27
  _NEWCOMMENTREQUEST._serialized_end=116
  _NEWCOMMENTRESPONSE._serialized_start=118
  _NEWCOMMENTRESPONSE._serialized_end=154
  _EDITCOMMENTREQUEST._serialized_start=156
  _EDITCOMMENTREQUEST._serialized_end=218
  _EDITCOMMENTRESPONSE._serialized_start=220
  _EDITCOMMENTRESPONSE._serialized_end=257
  _REMOVECOMMENTREQUEST._serialized_start=259
  _REMOVECOMMENTREQUEST._serialized_end=353
  _REMOVECOMMENTRESPONSE._serialized_start=355
  _REMOVECOMMENTRESPONSE._serialized_end=394
# @@protoc_insertion_point(module_scope)
