# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import name_pb2 as name__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x08\x63\x61shmere\x1a\nname.proto\"s\n\x08\x44\x61taInfo\x12%\n\tdata_type\x18\x01 \x01(\x0e\x32\x12.cashmere.DataType\x12\x17\n\x0fowner_manage_id\x18\x03 \x01(\x05\x12\x17\n\x0fowner_entity_id\x18\x04 \x01(\t\x12\x0e\n\x06stages\x18\x05 \x03(\t\"\x87\x01\n\x0eNewDataRequest\x12\x1c\n\x04name\x18\x01 \x01(\x0b\x32\x0e.cashmere.Name\x12%\n\tdata_type\x18\x02 \x01(\x0e\x32\x12.cashmere.DataType\x12\x17\n\x0fowner_manage_id\x18\x03 \x01(\x05\x12\x17\n\x0fowner_entity_id\x18\x04 \x01(\t\"!\n\x0fNewDataResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"%\n\x12GetDataInfoRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\"<\n\x13GetDataInfoResponse\x12%\n\tdata_info\x18\x01 \x01(\x0b\x32\x12.cashmere.DataInfo\"[\n\x16MarkDataRemovedRequest\x12\x17\n\x0fowner_manage_id\x18\x01 \x01(\x05\x12\x17\n\x0fowner_entity_id\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x61ta_id\x18\x03 \x01(\t\")\n\x17MarkDataRemovedResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"7\n\x0fListDataRequest\x12\x11\n\tmanage_id\x18\x01 \x01(\x05\x12\x11\n\tentity_id\x18\x02 \x01(\t\"$\n\x10ListDataResponse\x12\x10\n\x08\x64\x61ta_ids\x18\x01 \x03(\t*M\n\x08\x44\x61taType\x12\x0c\n\x08\x46ileData\x10\x00\x12\x10\n\x0cSequenceData\x10\x01\x12\x0f\n\x0b\x46ileSetData\x10\x02\x12\x10\n\x0c\x44ocumentData\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATATYPE._serialized_start=658
  _DATATYPE._serialized_end=735
  _DATAINFO._serialized_start=36
  _DATAINFO._serialized_end=151
  _NEWDATAREQUEST._serialized_start=154
  _NEWDATAREQUEST._serialized_end=289
  _NEWDATARESPONSE._serialized_start=291
  _NEWDATARESPONSE._serialized_end=324
  _GETDATAINFOREQUEST._serialized_start=326
  _GETDATAINFOREQUEST._serialized_end=363
  _GETDATAINFORESPONSE._serialized_start=365
  _GETDATAINFORESPONSE._serialized_end=425
  _MARKDATAREMOVEDREQUEST._serialized_start=427
  _MARKDATAREMOVEDREQUEST._serialized_end=518
  _MARKDATAREMOVEDRESPONSE._serialized_start=520
  _MARKDATAREMOVEDRESPONSE._serialized_end=561
  _LISTDATAREQUEST._serialized_start=563
  _LISTDATAREQUEST._serialized_end=618
  _LISTDATARESPONSE._serialized_start=620
  _LISTDATARESPONSE._serialized_end=656
# @@protoc_insertion_point(module_scope)
