# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x61ta_server.proto\x12\x08\x63\x61shmere\"\xe2\x02\n\x11\x44\x61taServerConfigs\x12\x15\n\rroot_dir_path\x18\x01 \x01(\t\x12\x15\n\rmax_file_size\x18\x02 \x01(\x04\x12\x14\n\x0cmax_set_size\x18\x03 \x01(\r\x12\x1b\n\x13max_sequence_length\x18\x04 \x01(\x04\x12\x1e\n\x16max_file_upload_number\x18\x05 \x01(\r\x12 \n\x18max_file_download_number\x18\x06 \x01(\r\x12\x1b\n\x13transfer_chunk_size\x18\x07 \x01(\r\x12R\n\x15internal_root_dir_map\x18\x08 \x03(\x0b\x32\x33.cashmere.DataServerConfigs.InternalRootDirMapEntry\x1a\x39\n\x17InternalRootDirMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1d\n\x1bGetDataServerConfigsRequest\"X\n\x1cGetDataServerConfigsResponse\x12\x38\n\x13\x64\x61ta_server_configs\x18\x01 \x01(\x0b\x32\x1b.cashmere.DataServerConfigsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATASERVERCONFIGS_INTERNALROOTDIRMAPENTRY._options = None
  _DATASERVERCONFIGS_INTERNALROOTDIRMAPENTRY._serialized_options = b'8\001'
  _DATASERVERCONFIGS._serialized_start=32
  _DATASERVERCONFIGS._serialized_end=386
  _DATASERVERCONFIGS_INTERNALROOTDIRMAPENTRY._serialized_start=329
  _DATASERVERCONFIGS_INTERNALROOTDIRMAPENTRY._serialized_end=386
  _GETDATASERVERCONFIGSREQUEST._serialized_start=388
  _GETDATASERVERCONFIGSREQUEST._serialized_end=417
  _GETDATASERVERCONFIGSRESPONSE._serialized_start=419
  _GETDATASERVERCONFIGSRESPONSE._serialized_end=507
# @@protoc_insertion_point(module_scope)
