# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_stage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x61ta_stage.proto\x12\x08\x63\x61shmere\"O\n\x13NewDataStageRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\x12\x12\n\nstage_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"&\n\x14NewDataStageResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"`\n!SetDataStageCurrentVersionRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\x12\x12\n\nstage_name\x18\x02 \x01(\t\x12\x16\n\x0etarget_version\x18\x03 \x01(\t\"4\n\"SetDataStageCurrentVersionResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"8\n\x16RemoveDataStageRequset\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\x12\r\n\x05stage\x18\x02 \x01(\t\")\n\x17RemoveDataStageResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"H\n\rDataStageInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08versions\x18\x02 \x03(\t\x12\x17\n\x0f\x63urrent_version\x18\x03 \x01(\t\"(\n\x15ListDataStagesRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\"A\n\x16ListDataStagesResponse\x12\'\n\x06stages\x18\x01 \x03(\x0b\x32\x17.cashmere.DataStageInfo\"R\n\x1a\x41\x64\x64\x44\x61taStageVersionRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\x12\x12\n\nstage_name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"-\n\x1b\x41\x64\x64\x44\x61taStageVersionResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"U\n\x1dRemoveDataStageVersionRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\x12\x12\n\nstage_name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"0\n\x1eRemoveDataStageVersionResponse\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_stage_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWDATASTAGEREQUEST._serialized_start=30
  _NEWDATASTAGEREQUEST._serialized_end=109
  _NEWDATASTAGERESPONSE._serialized_start=111
  _NEWDATASTAGERESPONSE._serialized_end=149
  _SETDATASTAGECURRENTVERSIONREQUEST._serialized_start=151
  _SETDATASTAGECURRENTVERSIONREQUEST._serialized_end=247
  _SETDATASTAGECURRENTVERSIONRESPONSE._serialized_start=249
  _SETDATASTAGECURRENTVERSIONRESPONSE._serialized_end=301
  _REMOVEDATASTAGEREQUSET._serialized_start=303
  _REMOVEDATASTAGEREQUSET._serialized_end=359
  _REMOVEDATASTAGERESPONSE._serialized_start=361
  _REMOVEDATASTAGERESPONSE._serialized_end=402
  _DATASTAGEINFO._serialized_start=404
  _DATASTAGEINFO._serialized_end=476
  _LISTDATASTAGESREQUEST._serialized_start=478
  _LISTDATASTAGESREQUEST._serialized_end=518
  _LISTDATASTAGESRESPONSE._serialized_start=520
  _LISTDATASTAGESRESPONSE._serialized_end=585
  _ADDDATASTAGEVERSIONREQUEST._serialized_start=587
  _ADDDATASTAGEVERSIONREQUEST._serialized_end=669
  _ADDDATASTAGEVERSIONRESPONSE._serialized_start=671
  _ADDDATASTAGEVERSIONRESPONSE._serialized_end=716
  _REMOVEDATASTAGEVERSIONREQUEST._serialized_start=718
  _REMOVEDATASTAGEVERSIONREQUEST._serialized_end=803
  _REMOVEDATASTAGEVERSIONRESPONSE._serialized_start=805
  _REMOVEDATASTAGEVERSIONRESPONSE._serialized_end=853
# @@protoc_insertion_point(module_scope)
