# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity_template.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65ntity_template.proto\x12\x08\x63\x61shmere\"=\n\x18NewEntityTemplateRequest\x12\x11\n\tmanage_id\x18\x01 \x01(\t\x12\x0e\n\x06\x66ields\x18\x02 \x03(\x0c\"+\n\x19NewEntityTemplateResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"@\n\x19\x45\x64itEntityTemplateRequest\x12\x13\n\x0btemplate_id\x18\x01 \x01(\t\x12\x0e\n\x06\x66ields\x18\x02 \x03(\x0c\",\n\x1a\x45\x64itEntityTemplateResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"2\n\x1bRemoveEntityTemplateRequest\x12\x13\n\x0btemplate_id\x18\x01 \x01(\t\".\n\x1cRemoveEntityTemplateResponse\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entity_template_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWENTITYTEMPLATEREQUEST._serialized_start=35
  _NEWENTITYTEMPLATEREQUEST._serialized_end=96
  _NEWENTITYTEMPLATERESPONSE._serialized_start=98
  _NEWENTITYTEMPLATERESPONSE._serialized_end=141
  _EDITENTITYTEMPLATEREQUEST._serialized_start=143
  _EDITENTITYTEMPLATEREQUEST._serialized_end=207
  _EDITENTITYTEMPLATERESPONSE._serialized_start=209
  _EDITENTITYTEMPLATERESPONSE._serialized_end=253
  _REMOVEENTITYTEMPLATEREQUEST._serialized_start=255
  _REMOVEENTITYTEMPLATEREQUEST._serialized_end=305
  _REMOVEENTITYTEMPLATERESPONSE._serialized_start=307
  _REMOVEENTITYTEMPLATERESPONSE._serialized_end=353
# @@protoc_insertion_point(module_scope)
