# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: epic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import name_pb2 as name__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nepic.proto\x12\nio.knitter\x1a\nname.proto\"l\n\x0eNewEpicRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x1c\n\x04name\x18\x02 \x01(\x0b\x32\x0e.cashmere.Name\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0btemplate_id\x18\x04 \x01(\t\"!\n\x0fNewEpicResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"*\n\x17GetEpicSequencesRequest\x12\x0f\n\x07\x65pic_id\x18\x01 \x01(\t\"-\n\x18GetEpicSequencesResponse\x12\x11\n\tsequences\x18\x01 \x03(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'epic_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWEPICREQUEST._serialized_start=38
  _NEWEPICREQUEST._serialized_end=146
  _NEWEPICRESPONSE._serialized_start=148
  _NEWEPICRESPONSE._serialized_end=181
  _GETEPICSEQUENCESREQUEST._serialized_start=183
  _GETEPICSEQUENCESREQUEST._serialized_end=225
  _GETEPICSEQUENCESRESPONSE._serialized_start=227
  _GETEPICSEQUENCESRESPONSE._serialized_end=272
# @@protoc_insertion_point(module_scope)
