# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65vent.proto\x12\x08\x63\x61shmere\"*\n\x05\x45vent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\x0c\"-\n\nEventQueue\x12\x11\n\tmanage_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"R\n\x0b\x45ventHandle\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\x12\x10\n\x08queue_id\x18\x02 \x01(\x05\x12\x11\n\tmanage_id\x18\x03 \x01(\x05\x12\x0c\n\x04name\x18\x04 \x01(\t\"8\n\x0fNewEventRequest\x12\x11\n\tmanage_id\x18\x02 \x01(\x05\x12\x12\n\nevent_name\x18\x01 \x01(\t\"\"\n\x10NewEventResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"8\n\x10\x45\x64itEventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\x12\x12\n\nnew_values\x18\x02 \x01(\x0c\"#\n\x11\x45\x64itEventResponse\x12\x0e\n\x06\x66\x61iled\x18\x01 \x01(\x08\"T\n\x1a\x41\x64\x64\x45ventTargetQueueRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\x12$\n\x06target\x18\x03 \x01(\x0b\x32\x14.cashmere.EventQueue\"-\n\x1b\x41\x64\x64\x45ventTargetQueueResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"7\n\x14NewEventQueueRequest\x12\x11\n\tmanage_id\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x01 \x01(\t\"\'\n\x15NewEventQueueResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"I\n\x15NewEventHandleRequest\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12\x10\n\x08queue_id\x18\x03 \x01(\x05\x12\x0c\n\x04name\x18\x04 \x01(\t\"(\n\x16NewEventHandleResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"2\n\x10\x45mitEventRequest\x12\x1e\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x0f.cashmere.Event\"#\n\x11\x45mitEventResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\")\n\x15LinkEventQueueRequest\x12\x10\n\x08queue_id\x18\x01 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVENT._serialized_start=25
  _EVENT._serialized_end=67
  _EVENTQUEUE._serialized_start=69
  _EVENTQUEUE._serialized_end=114
  _EVENTHANDLE._serialized_start=116
  _EVENTHANDLE._serialized_end=198
  _NEWEVENTREQUEST._serialized_start=200
  _NEWEVENTREQUEST._serialized_end=256
  _NEWEVENTRESPONSE._serialized_start=258
  _NEWEVENTRESPONSE._serialized_end=292
  _EDITEVENTREQUEST._serialized_start=294
  _EDITEVENTREQUEST._serialized_end=350
  _EDITEVENTRESPONSE._serialized_start=352
  _EDITEVENTRESPONSE._serialized_end=387
  _ADDEVENTTARGETQUEUEREQUEST._serialized_start=389
  _ADDEVENTTARGETQUEUEREQUEST._serialized_end=473
  _ADDEVENTTARGETQUEUERESPONSE._serialized_start=475
  _ADDEVENTTARGETQUEUERESPONSE._serialized_end=520
  _NEWEVENTQUEUEREQUEST._serialized_start=522
  _NEWEVENTQUEUEREQUEST._serialized_end=577
  _NEWEVENTQUEUERESPONSE._serialized_start=579
  _NEWEVENTQUEUERESPONSE._serialized_end=618
  _NEWEVENTHANDLEREQUEST._serialized_start=620
  _NEWEVENTHANDLEREQUEST._serialized_end=693
  _NEWEVENTHANDLERESPONSE._serialized_start=695
  _NEWEVENTHANDLERESPONSE._serialized_end=735
  _EMITEVENTREQUEST._serialized_start=737
  _EMITEVENTREQUEST._serialized_end=787
  _EMITEVENTRESPONSE._serialized_start=789
  _EMITEVENTRESPONSE._serialized_end=824
  _LINKEVENTQUEUEREQUEST._serialized_start=826
  _LINKEVENTQUEUEREQUEST._serialized_end=867
# @@protoc_insertion_point(module_scope)
