# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import file_info_pb2 as file__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66ile_data.proto\x12\x08\x63\x61shmere\x1a\x0f\x66ile_info.proto\"\xb7\x01\n\x19\x46ileDataUploadFileRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\x12\x14\n\x0ctotal_chunks\x18\x02 \x01(\x04\x12\x1b\n\x13\x63urrent_chunk_index\x18\x03 \x01(\x04\x12\r\n\x05\x63hunk\x18\x04 \x01(\x0c\x12\x11\n\tchunk_md5\x18\x06 \x01(\t\x12%\n\tfile_info\x18\x05 \x01(\x0b\x32\x12.cashmere.FileInfo\x12\r\n\x05stage\x18\x08 \x01(\t\"6\n\x1a\x46ileDataUploadFileResponse\x12\x18\n\x10next_chunk_index\x18\x01 \x01(\x04\"e\n\x1b\x46ileDataDownloadFileRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\x12\r\n\x05stage\x18\x02 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x03 \x01(\x04\x12\x11\n\tfile_name\x18\x04 \x01(\t\"\xa3\x01\n\x1c\x46ileDataDownloadFileResponse\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\x12\x14\n\x0ctotal_chunks\x18\x02 \x01(\x04\x12\x13\n\x0b\x63hunk_index\x18\x03 \x01(\x04\x12\r\n\x05\x63hunk\x18\x04 \x01(\x0c\x12\x11\n\tchunk_md5\x18\x05 \x01(\t\x12%\n\tfile_info\x18\x06 \x01(\x0b\x32\x12.cashmere.FileInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILEDATAUPLOADFILEREQUEST._serialized_start=47
  _FILEDATAUPLOADFILEREQUEST._serialized_end=230
  _FILEDATAUPLOADFILERESPONSE._serialized_start=232
  _FILEDATAUPLOADFILERESPONSE._serialized_end=286
  _FILEDATADOWNLOADFILEREQUEST._serialized_start=288
  _FILEDATADOWNLOADFILEREQUEST._serialized_end=389
  _FILEDATADOWNLOADFILERESPONSE._serialized_start=392
  _FILEDATADOWNLOADFILERESPONSE._serialized_end=555
# @@protoc_insertion_point(module_scope)
