# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import status_pb2 as status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\x12\x0f\x61\x63\x63ount_service\x1a\x0cstatus.proto\"E\n\x0cLoginRequest\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\".\n\rLoginResponse\x12\x0e\n\x06person\x18\x01 \x01(\x0c\x12\r\n\x05token\x18\x02 \x01(\t\"\x0f\n\rLogoutRequest\">\n\x0eLogoutResponse\x12,\n\x06result\x18\x01 \x01(\x0e\x32\x1c.account_service.LoginStatus\">\n\x19LoginWithValidCodeRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x12\n\nvalid_code\x18\x02 \x01(\t\",\n\x1aLoginWithValidCodeResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\'\n\x16GetValidateCodeRequest\x12\r\n\x05phone\x18\x01 \x01(\t\")\n\x17GetValidateCodeResponse\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUEST._serialized_start=46
  _LOGINREQUEST._serialized_end=115
  _LOGINRESPONSE._serialized_start=117
  _LOGINRESPONSE._serialized_end=163
  _LOGOUTREQUEST._serialized_start=165
  _LOGOUTREQUEST._serialized_end=180
  _LOGOUTRESPONSE._serialized_start=182
  _LOGOUTRESPONSE._serialized_end=244
  _LOGINWITHVALIDCODEREQUEST._serialized_start=246
  _LOGINWITHVALIDCODEREQUEST._serialized_end=308
  _LOGINWITHVALIDCODERESPONSE._serialized_start=310
  _LOGINWITHVALIDCODERESPONSE._serialized_end=354
  _GETVALIDATECODEREQUEST._serialized_start=356
  _GETVALIDATECODEREQUEST._serialized_end=395
  _GETVALIDATECODERESPONSE._serialized_start=397
  _GETVALIDATECODERESPONSE._serialized_end=438
# @@protoc_insertion_point(module_scope)
