# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: name.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nname.proto\x12\x08\x63\x61shmere\"&\n\x04Name\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"u\n\tNameField\x12\x36\n\nname_field\x18\x01 \x03(\x0b\x32\".cashmere.NameField.NameFieldEntry\x1a\x30\n\x0eNameFieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"Y\n\rRenameRequest\x12\x11\n\tmanage_id\x18\x01 \x01(\t\x12\x11\n\tentity_id\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x10\n\x08new_name\x18\x04 \x01(\t\" \n\x0eRenameResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"b\n\x16NewLanguageNameRequest\x12\x11\n\tmanage_id\x18\x01 \x01(\t\x12\x11\n\tentity_id\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x10\n\x08new_name\x18\x04 \x01(\t\")\n\x17NewLanguageNameResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"S\n\x19RemoveLanguageNameRequest\x12\x11\n\tmanage_id\x18\x01 \x01(\t\x12\x11\n\tentity_id\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\",\n\x1aRemoveLanguageNameResponse\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'name_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAMEFIELD_NAMEFIELDENTRY._options = None
  _NAMEFIELD_NAMEFIELDENTRY._serialized_options = b'8\001'
  _NAME._serialized_start=24
  _NAME._serialized_end=62
  _NAMEFIELD._serialized_start=64
  _NAMEFIELD._serialized_end=181
  _NAMEFIELD_NAMEFIELDENTRY._serialized_start=133
  _NAMEFIELD_NAMEFIELDENTRY._serialized_end=181
  _RENAMEREQUEST._serialized_start=183
  _RENAMEREQUEST._serialized_end=272
  _RENAMERESPONSE._serialized_start=274
  _RENAMERESPONSE._serialized_end=306
  _NEWLANGUAGENAMEREQUEST._serialized_start=308
  _NEWLANGUAGENAMEREQUEST._serialized_end=406
  _NEWLANGUAGENAMERESPONSE._serialized_start=408
  _NEWLANGUAGENAMERESPONSE._serialized_end=449
  _REMOVELANGUAGENAMEREQUEST._serialized_start=451
  _REMOVELANGUAGENAMEREQUEST._serialized_end=534
  _REMOVELANGUAGENAMERESPONSE._serialized_start=536
  _REMOVELANGUAGENAMERESPONSE._serialized_end=580
# @@protoc_insertion_point(module_scope)
