# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cperson.proto\x12\x08\x63\x61shmere\"\x1e\n\x10GetPersonRequest\x12\n\n\x02id\x18\x01 \x01(\t\"*\n\x16GetGroupPersonsRequest\x12\x10\n\x08group_id\x18\x01 \x01(\t\"3\n\x15GetPersonsPageRequest\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'person_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETPERSONREQUEST._serialized_start=26
  _GETPERSONREQUEST._serialized_end=56
  _GETGROUPPERSONSREQUEST._serialized_start=58
  _GETGROUPPERSONSREQUEST._serialized_end=100
  _GETPERSONSPAGEREQUEST._serialized_start=102
  _GETPERSONSPAGEREQUEST._serialized_end=153
# @@protoc_insertion_point(module_scope)
