# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phase.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import name_pb2 as name__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bphase.proto\x12\x08\x63\x61shmere\x1a\nname.proto\"E\n\x0fNewPhaseRequest\x12\x14\n\x0cprocedure_id\x18\x01 \x01(\t\x12\x1c\n\x04name\x18\x02 \x01(\x0b\x32\x0e.cashmere.Name\"\"\n\x10NewPhaseResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\":\n\x16MarkPhaseStatusRequest\x12\x10\n\x08phase_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\")\n\x17MarkPhaseStatusResponse\x12\x0e\n\x06result\x18\x01 \x01(\t*U\n\x0bPhaseStatus\x12\x10\n\x0cPhaseRunning\x10\x00\x12\x13\n\x0fPhaseSuspending\x10\x01\x12\x11\n\rPhaseCanceled\x10\x02\x12\x0c\n\x08PhaseEnd\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phase_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PHASESTATUS._serialized_start=247
  _PHASESTATUS._serialized_end=332
  _NEWPHASEREQUEST._serialized_start=37
  _NEWPHASEREQUEST._serialized_end=106
  _NEWPHASERESPONSE._serialized_start=108
  _NEWPHASERESPONSE._serialized_end=142
  _MARKPHASESTATUSREQUEST._serialized_start=144
  _MARKPHASESTATUSREQUEST._serialized_end=202
  _MARKPHASESTATUSRESPONSE._serialized_start=204
  _MARKPHASESTATUSRESPONSE._serialized_end=245
# @@protoc_insertion_point(module_scope)
