# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: procedure.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import name_pb2 as name__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprocedure.proto\x12\x08\x63\x61shmere\x1a\nname.proto\"H\n\x13NewProcedureRequest\x12\x1c\n\x04name\x18\x01 \x01(\x0b\x32\x0e.cashmere.Name\x12\x13\n\x0btemplate_id\x18\x02 \x01(\t\"&\n\x14NewProcedureResponse\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'procedure_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWPROCEDUREREQUEST._serialized_start=41
  _NEWPROCEDUREREQUEST._serialized_end=113
  _NEWPROCEDURERESPONSE._serialized_start=115
  _NEWPROCEDURERESPONSE._serialized_end=153
# @@protoc_insertion_point(module_scope)
