# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: property_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13property_type.proto\x12\x08\x63\x61shmere\"5\n\nInt32Range\x12\x0b\n\x03min\x18\x01 \x01(\x05\x12\x0b\n\x03max\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x05\"5\n\nInt64Range\x12\x0b\n\x03min\x18\x01 \x01(\x03\x12\x0b\n\x03max\x18\x02 \x01(\x03\x12\r\n\x05value\x18\x03 \x01(\x03\"6\n\x0bUInt32Range\x12\x0b\n\x03min\x18\x01 \x01(\r\x12\x0b\n\x03max\x18\x02 \x01(\r\x12\r\n\x05value\x18\x03 \x01(\r\"5\n\nFloatRange\x12\x0b\n\x03min\x18\x01 \x01(\x02\x12\x0b\n\x03max\x18\x02 \x01(\x02\x12\r\n\x05value\x18\x03 \x01(\x02\"6\n\x0b\x44oubleRange\x12\x0b\n\x03min\x18\x01 \x01(\x01\x12\x0b\n\x03max\x18\x02 \x01(\x01\x12\r\n\x05value\x18\x03 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'property_type_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INT32RANGE._serialized_start=33
  _INT32RANGE._serialized_end=86
  _INT64RANGE._serialized_start=88
  _INT64RANGE._serialized_end=141
  _UINT32RANGE._serialized_start=143
  _UINT32RANGE._serialized_end=197
  _FLOATRANGE._serialized_start=199
  _FLOATRANGE._serialized_end=252
  _DOUBLERANGE._serialized_start=254
  _DOUBLERANGE._serialized_end=308
# @@protoc_insertion_point(module_scope)
