# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: question.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0equestion.proto\x12\x08\x63\x61shmere\"F\n\x12NewQuestionRequest\x12\x10\n\x08graph_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63ontents\x18\x03 \x01(\t\"%\n\x13NewQuestionResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"R\n\x13\x45\x64itQuestionRequest\x12\x13\n\x0bquestion_id\x18\x02 \x01(\t\x12\x10\n\x08new_name\x18\x03 \x01(\t\x12\x14\n\x0cnew_contents\x18\x04 \x01(\t\"&\n\x14\x45\x64itQuestionResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\">\n\x15RemoveQuestionRequest\x12\x10\n\x08graph_id\x18\x01 \x01(\t\x12\x13\n\x0bquestion_id\x18\x02 \x01(\t\"(\n\x16RemoveQuestionResponse\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'question_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWQUESTIONREQUEST._serialized_start=28
  _NEWQUESTIONREQUEST._serialized_end=98
  _NEWQUESTIONRESPONSE._serialized_start=100
  _NEWQUESTIONRESPONSE._serialized_end=137
  _EDITQUESTIONREQUEST._serialized_start=139
  _EDITQUESTIONREQUEST._serialized_end=221
  _EDITQUESTIONRESPONSE._serialized_start=223
  _EDITQUESTIONRESPONSE._serialized_end=261
  _REMOVEQUESTIONREQUEST._serialized_start=263
  _REMOVEQUESTIONREQUEST._serialized_end=325
  _REMOVEQUESTIONRESPONSE._serialized_start=327
  _REMOVEQUESTIONRESPONSE._serialized_end=367
# @@protoc_insertion_point(module_scope)
