# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sequence.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import name_pb2 as name__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esequence.proto\x12\nio.knitter\x1a\nname.proto\"m\n\x12NewSequenceRequest\x12\x0f\n\x07\x65pic_id\x18\x01 \x01(\t\x12\x1c\n\x04name\x18\x02 \x01(\x0b\x32\x0e.cashmere.Name\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0btemplate_id\x18\x04 \x01(\t\"%\n\x13NewSequenceResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"-\n\x16GetSequenceCutsRequest\x12\x13\n\x0bsequence_id\x18\x01 \x01(\t\"\'\n\x17GetSequenceCutsResponse\x12\x0c\n\x04\x63uts\x18\x01 \x03(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sequence_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWSEQUENCEREQUEST._serialized_start=42
  _NEWSEQUENCEREQUEST._serialized_end=151
  _NEWSEQUENCERESPONSE._serialized_start=153
  _NEWSEQUENCERESPONSE._serialized_end=190
  _GETSEQUENCECUTSREQUEST._serialized_start=192
  _GETSEQUENCECUTSREQUEST._serialized_end=237
  _GETSEQUENCECUTSRESPONSE._serialized_start=239
  _GETSEQUENCECUTSRESPONSE._serialized_end=278
# @@protoc_insertion_point(module_scope)
