# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sequence_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13sequence_data.proto\x12\x08\x63\x61shmere\"\x9f\x01\n\x10SequenceDataInfo\x12\x13\n\x0bprefix_name\x18\x01 \x01(\t\x12\x18\n\x10sequence_pattern\x18\x02 \x01(\x04\x12\x13\n\x0btype_suffix\x18\x03 \x01(\x04\x12\x13\n\x0bstart_index\x18\x04 \x01(\x04\x12\x11\n\tend_index\x18\x05 \x01(\x04\x12\x12\n\ntotal_size\x18\x06 \x01(\x04\x12\x0b\n\x03md5\x18\x07 \x01(\t\"\xd1\x01\n!SequenceDataUploadSequenceRequest\x12\x15\n\rsequence_name\x18\x01 \x01(\t\x12\x16\n\x0eserial_pattern\x18\x02 \x01(\t\x12\x17\n\x0fsequence_length\x18\x03 \x01(\r\x12\x14\n\x0c\x63urrent_file\x18\x04 \x01(\t\x12\x15\n\rtotal_chancks\x18\x05 \x01(\x04\x12\x16\n\x0e\x63urrent_chunck\x18\x06 \x01(\x04\x12\x0e\n\x06\x63hunck\x18\x07 \x01(\x0c\x12\x0f\n\x07\x64\x61ta_id\x18\x08 \x01(\t\"4\n\"SequenceDataUploadSequenceResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"6\n#SequenceDataDownloadSequenceRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\"\xd4\x01\n$SequenceDataDownloadSequenceResponse\x12\x0f\n\x07\x64\x61ta_id\x18\x08 \x01(\t\x12\x15\n\rsequence_name\x18\x01 \x01(\t\x12\x16\n\x0eserial_pattern\x18\x02 \x01(\t\x12\x17\n\x0fsequence_length\x18\x03 \x01(\r\x12\x14\n\x0c\x63urrent_file\x18\x04 \x01(\t\x12\x15\n\rtotal_chancks\x18\x05 \x01(\x04\x12\x16\n\x0e\x63urrent_chunck\x18\x06 \x01(\x04\x12\x0e\n\x06\x63hunck\x18\x07 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sequence_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEQUENCEDATAINFO._serialized_start=34
  _SEQUENCEDATAINFO._serialized_end=193
  _SEQUENCEDATAUPLOADSEQUENCEREQUEST._serialized_start=196
  _SEQUENCEDATAUPLOADSEQUENCEREQUEST._serialized_end=405
  _SEQUENCEDATAUPLOADSEQUENCERESPONSE._serialized_start=407
  _SEQUENCEDATAUPLOADSEQUENCERESPONSE._serialized_end=459
  _SEQUENCEDATADOWNLOADSEQUENCEREQUEST._serialized_start=461
  _SEQUENCEDATADOWNLOADSEQUENCEREQUEST._serialized_end=515
  _SEQUENCEDATADOWNLOADSEQUENCERESPONSE._serialized_start=518
  _SEQUENCEDATADOWNLOADSEQUENCERESPONSE._serialized_end=730
# @@protoc_insertion_point(module_scope)
