# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import file_info_pb2 as file__info__pb2
import set_data_info_pb2 as set__data__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eset_data.proto\x12\x08\x63\x61shmere\x1a\x0f\x66ile_info.proto\x1a\x13set_data_info.proto\"(\n\x15GetSetDataInfoRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\"B\n\x16GetSetDataInfoResponse\x12(\n\tdata_info\x18\x01 \x01(\x0b\x32\x15.cashmere.SetDataInfo\"\x94\x01\n\x18SetDataUploadFileRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\x12\x14\n\x0ctotal_chunks\x18\x02 \x01(\x04\x12\x1b\n\x13\x63urrent_chunk_index\x18\x03 \x01(\x04\x12\r\n\x05\x63hunk\x18\x04 \x01(\x0c\x12%\n\tfile_info\x18\x05 \x01(\x0b\x32\x12.cashmere.FileInfo\"+\n\x19SetDataUploadFileResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\xb2\x01\n\x19SetDataUploadFilesRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\x12\x1c\n\x14\x63urrent_total_chunks\x18\x02 \x01(\x04\x12\x1b\n\x13\x63urrent_chunk_index\x18\x03 \x01(\x04\x12\r\n\x05\x63hunk\x18\x04 \x01(\x0c\x12%\n\tfile_info\x18\x05 \x03(\x0b\x32\x12.cashmere.FileInfo\x12\x13\n\x0b\x63urrent_md5\x18\x06 \x01(\t\",\n\x1aSetDataUploadFilesResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\",\n\x19SetDataDownloadSetRequest\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\"\xa9\x01\n\x1aSetDataDownloadSetResponse\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\x12\x10\n\x08set_name\x18\x02 \x01(\t\x12\x13\n\x0b\x66ile_counts\x18\x03 \x01(\r\x12\x14\n\x0c\x63urrent_file\x18\x04 \x01(\t\x12\x15\n\rtotal_chancks\x18\x05 \x01(\x04\x12\x16\n\x0e\x63urrent_chunck\x18\x06 \x01(\r\x12\x0e\n\x06\x63hunck\x18\x07 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'set_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETSETDATAINFOREQUEST._serialized_start=66
  _GETSETDATAINFOREQUEST._serialized_end=106
  _GETSETDATAINFORESPONSE._serialized_start=108
  _GETSETDATAINFORESPONSE._serialized_end=174
  _SETDATAUPLOADFILEREQUEST._serialized_start=177
  _SETDATAUPLOADFILEREQUEST._serialized_end=325
  _SETDATAUPLOADFILERESPONSE._serialized_start=327
  _SETDATAUPLOADFILERESPONSE._serialized_end=370
  _SETDATAUPLOADFILESREQUEST._serialized_start=373
  _SETDATAUPLOADFILESREQUEST._serialized_end=551
  _SETDATAUPLOADFILESRESPONSE._serialized_start=553
  _SETDATAUPLOADFILESRESPONSE._serialized_end=597
  _SETDATADOWNLOADSETREQUEST._serialized_start=599
  _SETDATADOWNLOADSETREQUEST._serialized_end=643
  _SETDATADOWNLOADSETRESPONSE._serialized_start=646
  _SETDATADOWNLOADSETRESPONSE._serialized_end=815
# @@protoc_insertion_point(module_scope)
