# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_collection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import name_pb2 as name__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14set_collection.proto\x12\nio.knitter\x1a\nname.proto\"\x92\x01\n\x17NewSetCollectionRequest\x12\x1c\n\x04name\x18\x01 \x01(\x0b\x32\x0e.cashmere.Name\x12\x17\n\x0finner_root_path\x18\x02 \x01(\t\x12\x1a\n\x12\x65xternal_root_path\x18\x03 \x01(\t\x12\x0f\n\x07picture\x18\x04 \x01(\x0c\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\"*\n\x18NewSetCollectionResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"e\n!GetSetCollectionAssetsPageRequest\x12\x12\n\nlibrary_id\x18\x01 \x01(\t\x12\x12\n\npage_index\x18\x02 \x01(\r\x12\x18\n\x10total_page_count\x18\x03 \x01(\r\"4\n\"GetSetCollectionAssetsPageResponse\x12\x0e\n\x06\x61ssets\x18\x01 \x03(\x0c\"i\n%GetSetCollectionAssembliesPageRequest\x12\x12\n\nlibrary_id\x18\x01 \x01(\t\x12\x12\n\npage_index\x18\x02 \x01(\r\x12\x18\n\x10total_page_count\x18\x03 \x01(\r\"8\n&GetSetCollectionAssembliesPageResponse\x12\x0e\n\x06\x61ssets\x18\x01 \x03(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'set_collection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWSETCOLLECTIONREQUEST._serialized_start=49
  _NEWSETCOLLECTIONREQUEST._serialized_end=195
  _NEWSETCOLLECTIONRESPONSE._serialized_start=197
  _NEWSETCOLLECTIONRESPONSE._serialized_end=239
  _GETSETCOLLECTIONASSETSPAGEREQUEST._serialized_start=241
  _GETSETCOLLECTIONASSETSPAGEREQUEST._serialized_end=342
  _GETSETCOLLECTIONASSETSPAGERESPONSE._serialized_start=344
  _GETSETCOLLECTIONASSETSPAGERESPONSE._serialized_end=396
  _GETSETCOLLECTIONASSEMBLIESPAGEREQUEST._serialized_start=398
  _GETSETCOLLECTIONASSEMBLIESPAGEREQUEST._serialized_end=503
  _GETSETCOLLECTIONASSEMBLIESPAGERESPONSE._serialized_start=505
  _GETSETCOLLECTIONASSEMBLIESPAGERESPONSE._serialized_end=561
# @@protoc_insertion_point(module_scope)
