# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_data_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import file_info_pb2 as file__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13set_data_info.proto\x12\x08\x63\x61shmere\x1a\x0f\x66ile_info.proto\"Z\n\x0bSetDataInfo\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\t\x12\x12\n\ntotal_size\x18\x02 \x01(\x04\x12&\n\nfile_infos\x18\x03 \x03(\x0b\x32\x12.cashmere.FileInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'set_data_info_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SETDATAINFO._serialized_start=50
  _SETDATAINFO._serialized_end=140
# @@protoc_insertion_point(module_scope)
