# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tag.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttag.proto\x12\x08\x63\x61shmere\"$\n\x03Tag\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61mmount\x18\x02 \x01(\x02\"]\n\rAddTagRequest\x12\x12\n\ntag_map_id\x18\x01 \x01(\t\x12\x10\n\x08point_id\x18\x02 \x01(\t\x12\x13\n\x0btag_type_id\x18\x03 \x01(\t\x12\x11\n\ttag_value\x18\x04 \x01(\x0c\" \n\x0e\x41\x64\x64TagResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"b\n\x12SetTagValueRequest\x12\x12\n\ntag_map_id\x18\x01 \x01(\t\x12\x10\n\x08point_id\x18\x02 \x01(\t\x12\x13\n\x0btag_type_id\x18\x03 \x01(\t\x12\x11\n\ttag_value\x18\x04 \x01(\x0c\"%\n\x13SetTagValueResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"M\n\x10RemoveTagRequest\x12\x12\n\ntag_map_id\x18\x01 \x01(\t\x12\x10\n\x08point_id\x18\x02 \x01(\t\x12\x13\n\x0btag_type_id\x18\x03 \x01(\t\"#\n\x11RemoveTagResponse\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tag_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TAG._serialized_start=23
  _TAG._serialized_end=59
  _ADDTAGREQUEST._serialized_start=61
  _ADDTAGREQUEST._serialized_end=154
  _ADDTAGRESPONSE._serialized_start=156
  _ADDTAGRESPONSE._serialized_end=188
  _SETTAGVALUEREQUEST._serialized_start=190
  _SETTAGVALUEREQUEST._serialized_end=288
  _SETTAGVALUERESPONSE._serialized_start=290
  _SETTAGVALUERESPONSE._serialized_end=327
  _REMOVETAGREQUEST._serialized_start=329
  _REMOVETAGREQUEST._serialized_end=406
  _REMOVETAGRESPONSE._serialized_start=408
  _REMOVETAGRESPONSE._serialized_end=443
# @@protoc_insertion_point(module_scope)
