# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tag_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import name_pb2 as name__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etag_type.proto\x12\x08\x63\x61shmere\x1a\nname.proto\"[\n\x11NewTagTypeRequest\x12\x11\n\tdomain_id\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\"$\n\x12NewTagTypeResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x9a\x01\n\x1c\x41\x64\x64\x44\x61taFieldToTagTypeRequest\x12\x13\n\x0btag_type_id\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x12\n\nfield_name\x18\x03 \x01(\t\x12(\n\tdata_type\x18\x04 \x01(\x0e\x32\x15.cashmere.TagDataType\x12\x15\n\rdefault_value\x18\x05 \x01(\x0c\"/\n\x1d\x41\x64\x64\x44\x61taFieldToTagTypeResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"^\n!RemoveDataFieldFromTagTypeRequest\x12\x13\n\x0btag_type_id\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x12\n\nfield_name\x18\x03 \x01(\t\"4\n\"RemoveDataFieldFromTagTypeResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"\xc0\x01\n\x1e\x45\x64itDataFieldForTagTypeRequest\x12\x13\n\x0btag_type_id\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x16\n\x0eold_field_name\x18\x03 \x01(\t\x12\x16\n\x0enew_field_name\x18\x04 \x01(\t\x12,\n\rnew_data_type\x18\x05 \x01(\x0e\x32\x15.cashmere.TagDataType\x12\x19\n\x11new_default_value\x18\x06 \x01(\x0c\"1\n\x1f\x45\x64itDataFieldForTagTypeResponse\x12\x0e\n\x06result\x18\x01 \x01(\t*X\n\x0bTagDataType\x12\n\n\x06Option\x10\x00\x12\x08\n\x04Text\x10\x01\x12\r\n\tDueration\x10\x02\x12\x08\n\x04\x44\x61te\x10\x03\x12\x0c\n\x08\x44\x61teTime\x10\x04\x12\x0c\n\x08Quantity\x10\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tag_type_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TAGDATATYPE._serialized_start=773
  _TAGDATATYPE._serialized_end=861
  _NEWTAGTYPEREQUEST._serialized_start=40
  _NEWTAGTYPEREQUEST._serialized_end=131
  _NEWTAGTYPERESPONSE._serialized_start=133
  _NEWTAGTYPERESPONSE._serialized_end=169
  _ADDDATAFIELDTOTAGTYPEREQUEST._serialized_start=172
  _ADDDATAFIELDTOTAGTYPEREQUEST._serialized_end=326
  _ADDDATAFIELDTOTAGTYPERESPONSE._serialized_start=328
  _ADDDATAFIELDTOTAGTYPERESPONSE._serialized_end=375
  _REMOVEDATAFIELDFROMTAGTYPEREQUEST._serialized_start=377
  _REMOVEDATAFIELDFROMTAGTYPEREQUEST._serialized_end=471
  _REMOVEDATAFIELDFROMTAGTYPERESPONSE._serialized_start=473
  _REMOVEDATAFIELDFROMTAGTYPERESPONSE._serialized_end=525
  _EDITDATAFIELDFORTAGTYPEREQUEST._serialized_start=528
  _EDITDATAFIELDFORTAGTYPEREQUEST._serialized_end=720
  _EDITDATAFIELDFORTAGTYPERESPONSE._serialized_start=722
  _EDITDATAFIELDFORTAGTYPERESPONSE._serialized_end=771
# @@protoc_insertion_point(module_scope)
