# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: view.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nview.proto\x12\x08\x63\x61shmere\"+\n\x14GetManageViewRequest\x12\x13\n\x0bmanage_name\x18\x01 \x01(\t\"+\n\x15GetManageViewResponse\x12\x12\n\nview_token\x18\x01 \x01(\t\"U\n\x1b\x43hangeManageReadRuleRequest\x12\x11\n\tmanage_id\x18\x01 \x01(\x05\x12\x10\n\x08group_id\x18\x02 \x01(\t\x12\x11\n\tread_rule\x18\x03 \x01(\t\".\n\x1c\x43hangeManageReadRuleResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"W\n\x1c\x43hangeManageWriteRuleRequest\x12\x11\n\tmanage_id\x18\x01 \x01(\x05\x12\x10\n\x08group_id\x18\x02 \x01(\t\x12\x12\n\nwrite_rule\x18\x03 \x01(\t\"/\n\x1d\x43hangeManageWriteRuleResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"Y\n\x1f\x43hangeCollectionReadRuleRequest\x12\x11\n\tmanage_id\x18\x01 \x01(\x05\x12\x10\n\x08group_id\x18\x02 \x01(\t\x12\x11\n\tread_rule\x18\x03 \x01(\t\"2\n ChangeCollectionReadRuleResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"[\n ChangeCollectionWriteRuleRequest\x12\x11\n\tmanage_id\x18\x01 \x01(\x05\x12\x10\n\x08group_id\x18\x02 \x01(\t\x12\x12\n\nwrite_rule\x18\x03 \x01(\t\"3\n!ChangeCollectionWriteRuleResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"f\n\x1a\x43hangeFieldReadRuleRequest\x12\x11\n\tmanage_id\x18\x01 \x01(\x05\x12\x10\n\x08group_id\x18\x02 \x01(\t\x12\x10\n\x08\x66ield_id\x18\x03 \x01(\t\x12\x11\n\tread_rule\x18\x04 \x01(\t\"-\n\x1b\x43hangeFieldReadRuleResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"h\n\x1b\x43hangeFieldWriteRuleRequest\x12\x11\n\tmanage_id\x18\x01 \x01(\x05\x12\x10\n\x08group_id\x18\x02 \x01(\t\x12\x10\n\x08\x66ield_id\x18\x03 \x01(\t\x12\x12\n\nwrite_rule\x18\x04 \x01(\t\".\n\x1c\x43hangeFieldWriteRuleResponse\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'view_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETMANAGEVIEWREQUEST._serialized_start=24
  _GETMANAGEVIEWREQUEST._serialized_end=67
  _GETMANAGEVIEWRESPONSE._serialized_start=69
  _GETMANAGEVIEWRESPONSE._serialized_end=112
  _CHANGEMANAGEREADRULEREQUEST._serialized_start=114
  _CHANGEMANAGEREADRULEREQUEST._serialized_end=199
  _CHANGEMANAGEREADRULERESPONSE._serialized_start=201
  _CHANGEMANAGEREADRULERESPONSE._serialized_end=247
  _CHANGEMANAGEWRITERULEREQUEST._serialized_start=249
  _CHANGEMANAGEWRITERULEREQUEST._serialized_end=336
  _CHANGEMANAGEWRITERULERESPONSE._serialized_start=338
  _CHANGEMANAGEWRITERULERESPONSE._serialized_end=385
  _CHANGECOLLECTIONREADRULEREQUEST._serialized_start=387
  _CHANGECOLLECTIONREADRULEREQUEST._serialized_end=476
  _CHANGECOLLECTIONREADRULERESPONSE._serialized_start=478
  _CHANGECOLLECTIONREADRULERESPONSE._serialized_end=528
  _CHANGECOLLECTIONWRITERULEREQUEST._serialized_start=530
  _CHANGECOLLECTIONWRITERULEREQUEST._serialized_end=621
  _CHANGECOLLECTIONWRITERULERESPONSE._serialized_start=623
  _CHANGECOLLECTIONWRITERULERESPONSE._serialized_end=674
  _CHANGEFIELDREADRULEREQUEST._serialized_start=676
  _CHANGEFIELDREADRULEREQUEST._serialized_end=778
  _CHANGEFIELDREADRULERESPONSE._serialized_start=780
  _CHANGEFIELDREADRULERESPONSE._serialized_end=825
  _CHANGEFIELDWRITERULEREQUEST._serialized_start=827
  _CHANGEFIELDWRITERULEREQUEST._serialized_end=931
  _CHANGEFIELDWRITERULERESPONSE._serialized_start=933
  _CHANGEFIELDWRITERULERESPONSE._serialized_end=979
# @@protoc_insertion_point(module_scope)
