# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: work.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nwork.proto\x12\x08\x63\x61shmere\"1\n\x0eNewWorkRequest\x12\x11\n\tmanage_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"!\n\x0fNewWorkResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"N\n\x15MarkWorkStatusRequest\x12\x0f\n\x07work_id\x18\x01 \x01(\t\x12$\n\x06status\x18\x02 \x01(\x0e\x32\x14.cashmere.WorkStatus\"(\n\x16MarkWorkStatusResponse\x12\x0e\n\x06result\x18\x01 \x01(\t*J\n\nWorkStatus\x12\x10\n\x0cWaitingStart\x10\x00\x12\x0e\n\nSuspending\x10\x01\x12\x0c\n\x08\x46inished\x10\x02\x12\x0c\n\x08\x43\x61nceled\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'work_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORKSTATUS._serialized_start=232
  _WORKSTATUS._serialized_end=306
  _NEWWORKREQUEST._serialized_start=24
  _NEWWORKREQUEST._serialized_end=73
  _NEWWORKRESPONSE._serialized_start=75
  _NEWWORKRESPONSE._serialized_end=108
  _MARKWORKSTATUSREQUEST._serialized_start=110
  _MARKWORKSTATUSREQUEST._serialized_end=188
  _MARKWORKSTATUSRESPONSE._serialized_start=190
  _MARKWORKSTATUSRESPONSE._serialized_end=230
# @@protoc_insertion_point(module_scope)
