# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: work_node.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import name_pb2 as name__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwork_node.proto\x12\x08\x63\x61shmere\x1a\nname.proto\"Y\n\x12NewWorkNodeRequest\x12\x10\n\x08phase_id\x18\x01 \x01(\t\x12\x1c\n\x04name\x18\x02 \x01(\x0b\x32\x0e.cashmere.Name\x12\x13\n\x0btemplate_id\x18\x03 \x01(\t\"%\n\x13NewWorkNodeResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"|\n\x19\x43reateWorkNodeLinkRequest\x12\x10\n\x08phase_id\x18\x01 \x01(\t\x12\x15\n\rstart_node_id\x18\x02 \x01(\t\x12\x10\n\x08out_slot\x18\x03 \x01(\t\x12\x13\n\x0b\x65nd_node_id\x18\x04 \x01(\t\x12\x0f\n\x07in_slot\x18\x05 \x01(\t\",\n\x1a\x43reateWorkNodeLinkResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"|\n\x19RemoveWorkNodeLinkRequest\x12\x10\n\x08phase_id\x18\x01 \x01(\t\x12\x15\n\rstart_node_id\x18\x02 \x01(\t\x12\x10\n\x08out_slot\x18\x03 \x01(\t\x12\x13\n\x0b\x65nd_node_id\x18\x04 \x01(\t\x12\x0f\n\x07in_slot\x18\x05 \x01(\t\",\n\x1aRemoveWorkNodeLinkResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"@\n\x15\x41ssignWorkNodeRequest\x12\x14\n\x0cwork_node_id\x18\x01 \x01(\t\x12\x11\n\tworker_id\x18\x02 \x01(\t\"(\n\x16\x41ssignWorkNodeResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"j\n\x1dNewDataSlotForWorkNodeRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12%\n\tslot_type\x18\x02 \x01(\x0e\x32\x12.cashmere.SlotType\x12\x11\n\tslot_name\x18\x03 \x01(\t\"0\n\x1eNewDataSlotForWorkNodeResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"F\n RemoveDataSlotForWorkNodeRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\tslot_name\x18\x02 \x01(\t\"3\n!RemoveDataSlotForWorkNodeResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"O\n\x18\x41\x64\x64\x44\x61taToDataSlotRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\tslot_name\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x61ta_id\x18\x03 \x01(\t\"+\n\x19\x41\x64\x64\x44\x61taToDataSlotResponse\x12\x0e\n\x06result\x18\x01 \x01(\t*I\n\x08SlotType\x12\x10\n\x0cRefrenceData\x10\x00\x12\x10\n\x0c\x44\x65pedentData\x10\x01\x12\x0c\n\x08WorkData\x10\x02\x12\x0b\n\x07OutData\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'work_node_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SLOTTYPE._serialized_start=1032
  _SLOTTYPE._serialized_end=1105
  _NEWWORKNODEREQUEST._serialized_start=41
  _NEWWORKNODEREQUEST._serialized_end=130
  _NEWWORKNODERESPONSE._serialized_start=132
  _NEWWORKNODERESPONSE._serialized_end=169
  _CREATEWORKNODELINKREQUEST._serialized_start=171
  _CREATEWORKNODELINKREQUEST._serialized_end=295
  _CREATEWORKNODELINKRESPONSE._serialized_start=297
  _CREATEWORKNODELINKRESPONSE._serialized_end=341
  _REMOVEWORKNODELINKREQUEST._serialized_start=343
  _REMOVEWORKNODELINKREQUEST._serialized_end=467
  _REMOVEWORKNODELINKRESPONSE._serialized_start=469
  _REMOVEWORKNODELINKRESPONSE._serialized_end=513
  _ASSIGNWORKNODEREQUEST._serialized_start=515
  _ASSIGNWORKNODEREQUEST._serialized_end=579
  _ASSIGNWORKNODERESPONSE._serialized_start=581
  _ASSIGNWORKNODERESPONSE._serialized_end=621
  _NEWDATASLOTFORWORKNODEREQUEST._serialized_start=623
  _NEWDATASLOTFORWORKNODEREQUEST._serialized_end=729
  _NEWDATASLOTFORWORKNODERESPONSE._serialized_start=731
  _NEWDATASLOTFORWORKNODERESPONSE._serialized_end=779
  _REMOVEDATASLOTFORWORKNODEREQUEST._serialized_start=781
  _REMOVEDATASLOTFORWORKNODEREQUEST._serialized_end=851
  _REMOVEDATASLOTFORWORKNODERESPONSE._serialized_start=853
  _REMOVEDATASLOTFORWORKNODERESPONSE._serialized_end=904
  _ADDDATATODATASLOTREQUEST._serialized_start=906
  _ADDDATATODATASLOTREQUEST._serialized_end=985
  _ADDDATATODATASLOTRESPONSE._serialized_start=987
  _ADDDATATODATASLOTRESPONSE._serialized_end=1030
# @@protoc_insertion_point(module_scope)
